image: node:latest

variables:
   npm_config_cache: "$CI_PROJECT_DIR/.npm"
   NODE_ENV: 'development'

services:
  - mongo
 

cache:
   key:
     files:
        - package.json
   paths:
      - .npm
      - node_modules

stages:
  - install
  - build
  - test
  - deploy
  - production

install_dependencies:
  stage: install
  script:
    - npm ci

build_netlify_functions:
  stage: build
  script:
    - npm run build

test_endpoint:
  stage: test
  script:
    - npm run test

deploy_staging:
  stage: deploy
  before_script:
    - npm install -g netlify-cli
  environment:
    name: deploy_staging
    url: $NETLIFY_DEVELOP_BUILD_URL
  script:
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
    - echo "Deployed to staging server"

deploy_production_develop:
  only:
    - develop
  stage: production
  before_script:
    - npm install -g netlify-cli
  environment:
    name: deploy_staging
    url: $NETLIFY_DEVELOP_BUILD_URL
  script:
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
    - echo "Deployed to production server"
  when: manual

deploy_production_master:
  only:
    - master
  stage: production
  before_script:
    - npm install -g netlify-cli
  environment:
    name: deploy_staging
    url: $NETLIFY_MASTER_BUILD_URL
  script:
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
    - echo "Deployed to production server"
