const stars = [
  {
    adult: false,
    gender: 2,
    id: 62,
    known_for: [
      {
        adult: false,
        backdrop_path: '/w7RDIgQM6bLT7JXtH4iUQd3Iwxm.jpg',
        genre_ids: [
          53,
          80,
        ],
        id: 680,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Pulp Fiction',
        overview: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
        poster_path: '/dRZpdpKLgN9nk57zggJCs1TjJb4.jpg',
        release_date: '1994-09-10',
        title: 'Pulp Fiction',
        video: false,
        vote_average: 8.5,
        vote_count: 20124,
      },
      {
        adult: false,
        backdrop_path: '/9pkZesKMnblFfKxEhQx45YQ2kIe.jpg',
        genre_ids: [
          27,
          53,
        ],
        id: 381288,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Split',
        overview: 'Though Kevin has evidenced 23 personalities to his trusted psychiatrist, Dr. Fletcher, there remains one still submerged who is set to materialize and dominate all the others. Compelled to abduct three teenage girls led by the willful, observant Casey, Kevin reaches a war for survival among all of those contained within him — as well as everyone around him — as the walls between his compartments shatter apart.',
        poster_path: '/bqb9WsmZmDIKxqYmBJ9lj7J6hzn.jpg',
        release_date: '2017-01-09',
        title: 'Split',
        video: false,
        vote_average: 7.3,
        vote_count: 13195,
      },
      {
        adult: false,
        backdrop_path: '/6TjllWT3cGrPFyqDXurVZ3L8bBi.jpg',
        genre_ids: [
          9648,
          53,
          18,
        ],
        id: 745,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'The Sixth Sense',
        overview: 'A psychological thriller about an eight year old boy named Cole Sear who believes he can see into the world of the dead. A child psychologist named Malcolm Crowe comes to Cole to help him deal with his problem, learning that he really can see the ghosts of dead people.',
        poster_path: '/fIssD3w3SvIhPPmVo4WMgZDVLID.jpg',
        release_date: '1999-08-06',
        title: 'The Sixth Sense',
        video: false,
        vote_average: 7.9,
        vote_count: 8107,
      },
    ],
    known_for_department: 'Acting',
    name: 'Bruce Willis',
    popularity: 46.738,
    profile_path: '/A1XBu3CffBpSK8HEIJM8q7Mn4lz.jpg',
  },
  {
    adult: false,
    gender: 1,
    id: 1734,
    known_for: [
      {
        backdrop_path: '/zlXPNnnUlyg6KyvvjGd2ZxG6Tnw.jpg',
        first_air_date: '2017-09-25',
        genre_ids: [
          18,
        ],
        id: 71712,
        media_type: 'tv',
        name: 'The Good Doctor',
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: 'The Good Doctor',
        overview: "A young surgeon with Savant syndrome is recruited into the surgical unit of a prestigious hospital. The question will arise: can a person who doesn't have the ability to relate to people actually save their lives?",
        poster_path: '/6tfT03sGp9k4c0J3dypjrI8TSAI.jpg',
        vote_average: 8.6,
        vote_count: 6135,
      },
      {
        backdrop_path: '/1ot3DeWBHaI3cbfQtqZqOI1VoPI.jpg',
        first_air_date: '1990-11-18',
        genre_ids: [
          18,
          9648,
          10765,
        ],
        id: 19614,
        media_type: 'tv',
        name: 'It',
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: 'It',
        overview: "In 1960, seven outcast kids known as \"The Losers' Club\" fight an evil demon who poses as a child-killing clown. Thirty years later, they reunite to stop the demon once and for all when it returns to their hometown.",
        poster_path: '/4ybQ6gopB3H3cu0seVZLznDnIKo.jpg',
        vote_average: 6.8,
        vote_count: 1984,
      },
      {
        backdrop_path: '/kuOt3LxmHW8k39SK2tyg6qSWhop.jpg',
        first_air_date: '2001-10-16',
        genre_ids: [
          10759,
          10765,
          18,
        ],
        id: 4604,
        media_type: 'tv',
        name: 'Smallville',
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: 'Smallville',
        overview: 'The origins of the world’s greatest hero–from Krypton refugee Kal-el’s arrival on Earth through his tumultuous teen years to Clark Kent’s final steps toward embracing his destiny as the Man of Steel.',
        poster_path: '/dc9a9n4g9Ibs485t5eBtyNG0mcr.jpg',
        vote_average: 8.1,
        vote_count: 1887,
      },
    ],
    known_for_department: 'Acting',
    name: "Annette O'Toole",
    popularity: 45.263,
    profile_path: '/z5BS5EeuhpM2KGFfUjOhVXtjmMy.jpg',
  },
  {
    adult: false,
    gender: 1,
    id: 1397778,
    known_for: [
      {
        adult: false,
        backdrop_path: '/9pkZesKMnblFfKxEhQx45YQ2kIe.jpg',
        genre_ids: [
          27,
          53,
        ],
        id: 381288,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Split',
        overview: 'Though Kevin has evidenced 23 personalities to his trusted psychiatrist, Dr. Fletcher, there remains one still submerged who is set to materialize and dominate all the others. Compelled to abduct three teenage girls led by the willful, observant Casey, Kevin reaches a war for survival among all of those contained within him — as well as everyone around him — as the walls between his compartments shatter apart.',
        poster_path: '/bqb9WsmZmDIKxqYmBJ9lj7J6hzn.jpg',
        release_date: '2017-01-09',
        title: 'Split',
        video: false,
        vote_average: 7.3,
        vote_count: 13194,
      },
      {
        adult: false,
        backdrop_path: '/ngBFDOsx13sFXiMweDoL54XYknR.jpg',
        genre_ids: [
          53,
          18,
          878,
        ],
        id: 450465,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Glass',
        overview: 'In a series of escalating encounters, former security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities. Meanwhile, the shadowy presence of Elijah Price emerges as an orchestrator who holds secrets critical to both men.',
        poster_path: '/svIDTNUoajS8dLEo7EosxvyAsgJ.jpg',
        release_date: '2019-01-16',
        title: 'Glass',
        video: false,
        vote_average: 6.6,
        vote_count: 5791,
      },
      {
        adult: false,
        backdrop_path: '/n2UXRCLkxtukYGXYYKEIGrm6zJn.jpg',
        genre_ids: [
          27,
          18,
          9648,
          36,
        ],
        id: 310131,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'The Witch',
        overview: 'In 1630s New England, William and Katherine lead a devout Christian life with five children, homesteading on the edge of an impassable wilderness, exiled from their settlement when William defies the local church. When their newborn son vanishes and crops mysteriously fail, the family turns on one another.',
        poster_path: '/o384OC1tCV8nCnozkM6y4MiSqsw.jpg',
        release_date: '2015-11-11',
        title: 'The Witch',
        video: false,
        vote_average: 6.8,
        vote_count: 4281,
      },
    ],
    known_for_department: 'Acting',
    name: 'Anya Taylor-Joy',
    popularity: 42.447,
    profile_path: '/1zA5GuTcciupj4PsNoV2YemB0Wm.jpg',
  },
  {
    adult: false,
    gender: 1,
    id: 1245,
    known_for: [
      {
        adult: false,
        backdrop_path: '/kwUQFeFXOOpgloMgZaadhzkbTI4.jpg',
        genre_ids: [
          878,
          28,
          12,
        ],
        id: 24428,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'The Avengers',
        overview: 'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!',
        poster_path: '/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
        release_date: '2012-04-25',
        title: 'The Avengers',
        video: false,
        vote_average: 7.7,
        vote_count: 23641,
      },
      {
        adult: false,
        backdrop_path: '/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg',
        genre_ids: [
          12,
          28,
          878,
        ],
        id: 299536,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Avengers: Infinity War',
        overview: 'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
        poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
        release_date: '2018-04-25',
        title: 'Avengers: Infinity War',
        video: false,
        vote_average: 8.3,
        vote_count: 20441,
      },
      {
        adult: false,
        backdrop_path: '/7FWlcZq3r6525LWOcvO9kNWurN1.jpg',
        genre_ids: [
          12,
          28,
          878,
        ],
        id: 271110,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Captain America: Civil War',
        overview: 'Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.',
        poster_path: '/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg',
        release_date: '2016-04-27',
        title: 'Captain America: Civil War',
        video: false,
        vote_average: 7.4,
        vote_count: 17195,
      },
    ],
    known_for_department: 'Acting',
    name: 'Scarlett Johansson',
    popularity: 36.1,
    profile_path: '/6NsMbJXRlDZuDzatN2akFdGuTvx.jpg',
  },
  {
    adult: false,
    gender: 2,
    id: 500,
    known_for: [
      {
        adult: false,
        backdrop_path: '/auZIuHEUec5tBTns3tCRXfayxZq.jpg',
        genre_ids: [
          28,
          878,
        ],
        id: 137113,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Edge of Tomorrow',
        overview: 'Major Bill Cage is an officer who has never seen a day of combat when he is unceremoniously demoted and dropped into combat. Cage is killed within minutes, managing to take an alpha alien down with him. He awakens back at the beginning of the same day and is forced to fight and die again... and again - as physical contact with the alien has thrown him into a time loop.',
        poster_path: '/uUHvlkLavotfGsNtosDy8ShsIYF.jpg',
        release_date: '2014-05-27',
        title: 'Edge of Tomorrow',
        video: false,
        vote_average: 7.6,
        vote_count: 10095,
      },
      {
        adult: false,
        backdrop_path: '/Pv6vu1lxgct3GWhUXVVOMZwNlZ.jpg',
        genre_ids: [
          28,
          878,
          12,
          9648,
        ],
        id: 75612,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Oblivion',
        overview: 'Jack Harper is one of the last few drone repairmen stationed on Earth.  Part of a massive operation to extract vital resources after decades of war with a terrifying threat known as the Scavs, Jack’s mission is nearly complete.  His existence is brought crashing down when he rescues a beautiful  stranger from a downed spacecraft.  Her arrival triggers a chain of events that  forces him to question everything he knows and puts the fate of humanity in his hands.',
        poster_path: '/2ncs7hqBsEjFMqt6Y7ShBCO9tWs.jpg',
        release_date: '2013-04-10',
        title: 'Oblivion',
        video: false,
        vote_average: 6.6,
        vote_count: 8265,
      },
      {
        adult: false,
        backdrop_path: '/hqyjzDRCs1N5gEsh2gklzPdsEFD.jpg',
        genre_ids: [
          28,
          53,
          12,
        ],
        id: 56292,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Mission: Impossible - Ghost Protocol',
        overview: 'Ethan Hunt and his team are racing against time to track down a dangerous terrorist named Hendricks, who has gained access to Russian nuclear launch codes and is planning a strike on the United States. An attempt to stop him ends in an explosion causing severe destruction to the Kremlin and the IMF to be implicated in the bombing, forcing the President to disavow them. No longer being aided by the government, Ethan and his team chase Hendricks around the globe, although they might still be too late to stop a disaster.',
        poster_path: '/7GCKNRbzcA4rJXAKoE8KS9IDnZP.jpg',
        release_date: '2011-12-07',
        title: 'Mission: Impossible - Ghost Protocol',
        video: false,
        vote_average: 7,
        vote_count: 7343,
      },
    ],
    known_for_department: 'Acting',
    name: 'Tom Cruise',
    popularity: 34.504,
    profile_path: '/gThaIXgpCm3PCiXwFNDBJCme85y.jpg',
  },
  {
    adult: false,
    gender: 1,
    id: 1813,
    known_for: [
      {
        adult: false,
        backdrop_path: '/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
        genre_ids: [
          12,
          18,
          878,
        ],
        id: 157336,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Interstellar',
        overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
        poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        release_date: '2014-11-05',
        title: 'Interstellar',
        video: false,
        vote_average: 8.3,
        vote_count: 24503,
      },
      {
        adult: false,
        backdrop_path: '/cKPfiu9IcCW0fMdKdQBXe3PRtTZ.jpg',
        genre_ids: [
          28,
          80,
          18,
          53,
        ],
        id: 49026,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'The Dark Knight Rises',
        overview: "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
        poster_path: '/vzvKcPQ4o7TjWeGIn0aGC9FeVNu.jpg',
        release_date: '2012-07-16',
        title: 'The Dark Knight Rises',
        video: false,
        vote_average: 7.7,
        vote_count: 17051,
      },
      {
        adult: false,
        backdrop_path: '/20pkC7yJdCV4J1IMKfsCT9QU7zV.jpg',
        genre_ids: [
          10751,
          14,
          12,
        ],
        id: 12155,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Alice in Wonderland',
        overview: "Alice, an unpretentious and individual 19-year-old, is betrothed to a dunce of an English nobleman. At her engagement party, she escapes the crowd to consider whether to go through with the marriage and falls down a hole in the garden after spotting an unusual rabbit. Arriving in a strange and surreal place called 'Underland,' she finds herself in a world that resembles the nightmares she had as a child, filled with talking animals, villainous queens and knights, and frumious bandersnatches. Alice realizes that she is there for a reason – to conquer the horrific Jabberwocky and restore the rightful queen to her throne.",
        poster_path: '/o0kre9wRCZz3jjSjaru7QU0UtFz.jpg',
        release_date: '2010-03-03',
        title: 'Alice in Wonderland',
        video: false,
        vote_average: 6.6,
        vote_count: 10812,
      },
    ],
    known_for_department: 'Acting',
    name: 'Anne Hathaway',
    popularity: 34.363,
    profile_path: '/tLelKoPNiyJCSEtQTz1FGv4TLGc.jpg',
  },
  {
    adult: false,
    gender: 2,
    id: 48,
    known_for: [
      {
        adult: false,
        backdrop_path: '/vRQnzOn4HjIMX4LBq9nHhFXbsSu.jpg',
        genre_ids: [
          12,
          14,
          28,
        ],
        id: 120,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'The Lord of the Rings: The Fellowship of the Ring',
        overview: 'Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.',
        poster_path: '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
        release_date: '2001-12-18',
        title: 'The Lord of the Rings: The Fellowship of the Ring',
        video: false,
        vote_average: 8.3,
        vote_count: 18216,
      },
      {
        adult: false,
        backdrop_path: '/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg',
        genre_ids: [
          12,
          14,
          28,
        ],
        id: 122,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'The Lord of the Rings: The Return of the King',
        overview: "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
        poster_path: '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
        release_date: '2003-12-01',
        title: 'The Lord of the Rings: The Return of the King',
        video: false,
        vote_average: 8.5,
        vote_count: 16761,
      },
      {
        adult: false,
        backdrop_path: '/7tNTPZMb13W0AhkcuoL6myRrNRr.jpg',
        genre_ids: [
          12,
          14,
          28,
        ],
        id: 121,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'The Lord of the Rings: The Two Towers',
        overview: 'Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.',
        poster_path: '/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg',
        release_date: '2002-12-18',
        title: 'The Lord of the Rings: The Two Towers',
        video: false,
        vote_average: 8.3,
        vote_count: 15730,
      },
    ],
    known_for_department: 'Acting',
    name: 'Sean Bean',
    popularity: 33.217,
    profile_path: '/kTjiABk3TJ3yI0Cto5RsvyT6V3o.jpg',
  },
  {
    adult: false,
    gender: 2,
    id: 3,
    known_for: [
      {
        adult: false,
        backdrop_path: '/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg',
        genre_ids: [
          28,
          12,
          878,
          14,
        ],
        id: 140607,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Star Wars: The Force Awakens',
        overview: 'Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.',
        poster_path: '/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg',
        release_date: '2015-12-15',
        title: 'Star Wars: The Force Awakens',
        video: false,
        vote_average: 7.4,
        vote_count: 15226,
      },
      {
        adult: false,
        backdrop_path: '/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg',
        genre_ids: [
          12,
          28,
          878,
        ],
        id: 11,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Star Wars',
        overview: 'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.',
        poster_path: '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
        release_date: '1977-05-25',
        title: 'Star Wars',
        video: false,
        vote_average: 8.2,
        vote_count: 14750,
      },
      {
        adult: false,
        backdrop_path: '/dMZxEdrWIzUmUoOz2zvmFuutbj7.jpg',
        genre_ids: [
          12,
          28,
          878,
        ],
        id: 1891,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'The Empire Strikes Back',
        overview: 'The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.',
        poster_path: '/7BuH8itoSrLExs2YZSsM01Qk2no.jpg',
        release_date: '1980-05-20',
        title: 'The Empire Strikes Back',
        video: false,
        vote_average: 8.4,
        vote_count: 12335,
      },
    ],
    known_for_department: 'Acting',
    name: 'Harrison Ford',
    popularity: 32.805,
    profile_path: '/6MQgrJvdTPFvyErIgn0B2lTLVhr.jpg',
  },
  {
    adult: false,
    gender: 2,
    id: 976,
    known_for: [
      {
        adult: false,
        backdrop_path: '/oqxCzAO8sn1rSco2Pc19DlitgEn.jpg',
        genre_ids: [
          28,
          53,
          80,
        ],
        id: 82992,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Fast & Furious 6',
        overview: 'Hobbs has Dominic and Brian reassemble their crew to take down a team of mercenaries: Dominic unexpectedly gets convoluted also facing his presumed deceased girlfriend, Letty.',
        poster_path: '/n31VRDodbaZxkrZmmzyYSFNVpW5.jpg',
        release_date: '2013-05-21',
        title: 'Fast & Furious 6',
        video: false,
        vote_average: 6.8,
        vote_count: 8289,
      },
      {
        adult: false,
        backdrop_path: '/vkQvqH8WQkUiNklDcbUtHEUgSNQ.jpg',
        genre_ids: [
          28,
          53,
        ],
        id: 168259,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Furious 7',
        overview: 'Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.',
        poster_path: '/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg',
        release_date: '2015-04-01',
        title: 'Furious 7',
        video: false,
        vote_average: 7.3,
        vote_count: 7958,
      },
      {
        adult: false,
        backdrop_path: '/jzdnhRhG0dsuYorwvSqPqqnM1cV.jpg',
        genre_ids: [
          28,
          80,
          53,
        ],
        id: 337339,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'The Fate of the Furious',
        overview: 'When a mysterious woman seduces Dom into the world of crime and a betrayal of those closest to him, the crew face trials that will test them as never before.',
        poster_path: '/dImWM7GJqryWJO9LHa3XQ8DD5NH.jpg',
        release_date: '2017-04-12',
        title: 'The Fate of the Furious',
        video: false,
        vote_average: 6.9,
        vote_count: 7833,
      },
    ],
    known_for_department: 'Acting',
    name: 'Jason Statham',
    popularity: 30.588,
    profile_path: '/lldeQ91GwIVff43JBrpdbAAeYWj.jpg',
  },
  {
    adult: false,
    gender: 1,
    id: 90633,
    known_for: [
      {
        adult: false,
        backdrop_path: '/6iUNJZymJBMXXriQyFZfLAKnjO6.jpg',
        genre_ids: [
          28,
          12,
          14,
        ],
        id: 297762,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Wonder Woman',
        overview: 'An Amazon princess comes to the world of Man in the grips of the First World War to confront the forces of evil and bring an end to human conflict.',
        poster_path: '/gfJGlDaHuWimErCr5Ql0I8x9QSy.jpg',
        release_date: '2017-05-30',
        title: 'Wonder Woman',
        video: false,
        vote_average: 7.3,
        vote_count: 15580,
      },
      {
        adult: false,
        backdrop_path: '/doiUtOHzcxXFl0GVQ2n8Ay6Pirx.jpg',
        genre_ids: [
          28,
          12,
          14,
        ],
        id: 209112,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Batman v Superman: Dawn of Justice',
        overview: 'Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.',
        poster_path: '/5UsK3grJvtQrtzEgqNlDljJW96w.jpg',
        release_date: '2016-03-23',
        title: 'Batman v Superman: Dawn of Justice',
        video: false,
        vote_average: 5.9,
        vote_count: 14088,
      },
      {
        adult: false,
        backdrop_path: '/jorgjEk6a0bed6jdR5wu4S6ZvRm.jpg',
        genre_ids: [
          28,
          12,
          14,
          878,
        ],
        id: 141052,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Justice League',
        overview: "Fuelled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne and Diana Prince assemble a team of metahumans consisting of Barry Allen, Arthur Curry and Victor Stone to face the catastrophic threat of Steppenwolf and the Parademons who are on the hunt for three Mother Boxes on Earth.",
        poster_path: '/eifGNCSDuxJeS1loAXil5bIGgvC.jpg',
        release_date: '2017-11-15',
        title: 'Justice League',
        video: false,
        vote_average: 6.2,
        vote_count: 9913,
      },
    ],
    known_for_department: 'Acting',
    name: 'Gal Gadot',
    popularity: 28.151,
    profile_path: '/aDWrs64fKhIyqeIMPTAlK4UlDbZ.jpg',
  },
  {
    adult: false,
    gender: 1,
    id: 2025252,
    known_for: [
      {
        backdrop_path: '/1qOA3kMtQO8bjnW8M2smjA8tp10.jpg',
        first_air_date: '2018-10-05',
        genre_ids: [
          80,
          9648,
          18,
        ],
        id: 76669,
        media_type: 'tv',
        name: 'Elite',
        origin_country: [
          'ES',
        ],
        original_language: 'es',
        original_name: 'Élite',
        overview: 'When three working class kids enroll in the most exclusive school in Spain, the clash between the wealthy and the poor students leads to tragedy.',
        poster_path: '/3NTAbAiao4JLzFQw6YxP1YZppM8.jpg',
        vote_average: 8.3,
        vote_count: 5535,
      },
      {
        backdrop_path: '/iukGFUQQWUdgwTGGDLb1Pw3GoZP.jpg',
        first_air_date: '2015-04-20',
        genre_ids: [
          18,
        ],
        id: 62455,
        media_type: 'tv',
        name: 'Locked Up',
        origin_country: [
          'ES',
        ],
        original_language: 'es',
        original_name: 'Vis a vis',
        overview: "Set up to take the blame for corporate fraud, young Macarena Ferreiro is locked up in a high-security women's prison surrounded by tough, ruthless criminals in this tense, provocative Spanish thriller.",
        poster_path: '/1kH9u5DkoDUuIlhFFWjz9VSlKhC.jpg',
        vote_average: 8,
        vote_count: 1668,
      },
      {
        adult: false,
        backdrop_path: '/92oqNzaQrXbqc7ewO2BPfnLBVvi.jpg',
        genre_ids: [
          28,
          80,
          53,
        ],
        id: 394684,
        media_type: 'movie',
        original_language: 'es',
        original_title: 'Que Dios nos perdone',
        overview: 'Madrid, summer 2011. Economic crisis. 15-M movement and 1.5 million pilgrims waiting for the Pope’s arrival live side by side in a Madrid that’s hotter and more chaotic than ever. In this context, detectives Velarde and Alfaro must find what seems to be a serial killer. Their against-the-clock hunt will make them realise something they’d never imagined: neither of them are so very different from the killer.',
        poster_path: '/4TfKiRHBEJvGTyuGO05OPcHm226.jpg',
        release_date: '2016-10-28',
        title: 'May God Save Us',
        video: false,
        vote_average: 6.7,
        vote_count: 271,
      },
    ],
    known_for_department: 'Acting',
    name: 'Ester Expósito',
    popularity: 27.961,
    profile_path: '/hCbXPMVo0x0ZKGNyelvOvqKYCsL.jpg',
  },
  {
    adult: false,
    gender: 2,
    id: 1533800,
    known_for: [
      {
        adult: false,
        backdrop_path: '/8BGweIbTiSIsPYCzedhkEPNhIuq.jpg',
        genre_ids: [
          10770,
          10749,
          18,
          14,
          9648,
        ],
        id: 367544,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'The Spirit of Christmas',
        overview: 'A woman falls in love with a man who is somewhat unavailable.',
        poster_path: '/ynWcaW8ZrtBeuzgUyEXR30A2TAT.jpg',
        release_date: '2015-11-28',
        title: 'The Spirit of Christmas',
        video: false,
        vote_average: 6.8,
        vote_count: 192,
      },
      {
        adult: false,
        backdrop_path: '/5HMI9BlTzmc8ZckJPmp7nFAqhOv.jpg',
        genre_ids: [
          10749,
          10770,
        ],
        id: 493762,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Love on the Slopes',
        overview: 'NYC-based copy editor, Alex, is sent to Ridgeline Resort, an extreme sports outpost, to write a story for a travel writing competition. At first, she fails at everything – much to the chagrin of Cole, an extreme sports enthusiast who thinks this city girl should head back to New York. But when Alex offers to assist Cole with his local arts festival, he reluctantly obliges to be her guide as she faces her fears doing one extreme sport after the next.',
        poster_path: '/1YVFAR9EkvVhUrKjg4TsA6nD621.jpg',
        release_date: '2018-01-06',
        title: 'Love on the Slopes',
        video: false,
        vote_average: 6.3,
        vote_count: 44,
      },
      {
        adult: false,
        backdrop_path: '/hm2QRQp0hFgGyaiNRpWL71XV0tM.jpg',
        genre_ids: [
          10749,
        ],
        id: 463314,
        media_type: 'movie',
        original_language: 'en',
        original_title: "Love's Last Resort",
        overview: 'In an effort to force her boyfriend to grow up, Chloe breaks up with him thinking that he will crawl back to her. Instead, she does not hear from him for six months until she finally bumps into him only to find out that he is getting married.',
        poster_path: '/613bOTKlqbQpVBWMyAaTNHmAJfN.jpg',
        release_date: '2017-06-17',
        title: "Love's Last Resort",
        video: false,
        vote_average: 5.8,
        vote_count: 31,
      },
    ],
    known_for_department: 'Acting',
    name: 'Thomas Beaudoin',
    popularity: 27.273,
    profile_path: '/bCJfHKARr8ArNM9U7hRuCcsozPm.jpg',
  },
  {
    adult: false,
    gender: 2,
    id: 85,
    known_for: [
      {
        adult: false,
        backdrop_path: '/jOh79POQu4hyVIseUxdQxTW7vOf.jpg',
        genre_ids: [
          12,
          14,
          28,
        ],
        id: 22,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Pirates of the Caribbean: The Curse of the Black Pearl',
        overview: "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster_path: '/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg',
        release_date: '2003-07-09',
        title: 'Pirates of the Caribbean: The Curse of the Black Pearl',
        video: false,
        vote_average: 7.7,
        vote_count: 15323,
      },
      {
        adult: false,
        backdrop_path: '/7GrpqAs0oDcFcwFwyygnUI7BrZA.jpg',
        genre_ids: [
          12,
          14,
        ],
        id: 259316,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Fantastic Beasts and Where to Find Them',
        overview: 'In 1926, Newt Scamander arrives at the Magical Congress of the United States of America with a magically expanded briefcase, which houses a number of dangerous creatures and their habitats. When the creatures escape from the briefcase, it sends the American wizarding authorities after Newt, and threatens to strain even further the state of magical and non-magical relations.',
        poster_path: '/fLsaFKExQt05yqjoAvKsmOMYvJR.jpg',
        release_date: '2016-11-16',
        title: 'Fantastic Beasts and Where to Find Them',
        video: false,
        vote_average: 7.4,
        vote_count: 14798,
      },
      {
        adult: false,
        backdrop_path: '/5gPPx16QWx071VAI1M0RAVKJ6tc.jpg',
        genre_ids: [
          12,
          14,
          28,
        ],
        id: 58,
        media_type: 'movie',
        original_language: 'en',
        original_title: "Pirates of the Caribbean: Dead Man's Chest",
        overview: 'Captain Jack Sparrow works his way out of a blood debt with the ghostly Davy Jones to avoid eternal damnation.',
        poster_path: '/l3peI54mf6Z9EBSvS3hnRmOBbFT.jpg',
        release_date: '2006-07-06',
        title: "Pirates of the Caribbean: Dead Man's Chest",
        video: false,
        vote_average: 7.3,
        vote_count: 11688,
      },
    ],
    known_for_department: 'Acting',
    name: 'Johnny Depp',
    popularity: 27.226,
    profile_path: '/ilPBHd3r3ahlipNQtjr4E3G04jJ.jpg',
  },
]

export { stars }
